Module7 task2
htmlacademy-nodejs/461957-typoteka-3 pull request #30
Opened 2021-02-21 13:09 UTC by artembert

2021-02-24 15:03 UTC, LordotU requested changes

2021-02-24 15:03 UTC, LordotU commented on src/service/server/data-access/services/users.service.ts
> +    return user.get();
В этом методе и другом `find`, кажись, засада: в переменную `user` попадает либо инстанс соотв. модели, либо `null`. Соотв., тут получается не очень

2021-02-24 15:03 UTC, LordotU commented on src/service/server/data-access/services/users.service.ts
> +    return user.get();
В этом методе и другом `find`, кажись, засада: в переменную `user` попадает либо инстанс соотв. модели, либо `null`. Соотв., тут получается не очень

2021-02-24 15:03 UTC, LordotU commented on src/service/server/controllers/users.controller.ts
> +    try {
В силу описанного в комментарии для модели пользователя, отдача результата через `try/catch` - не очень. Нужна явная  проверка

2021-02-24 15:03 UTC, LordotU commented on src/service/server/data-access/fill-db.ts
> +  return [...uniqueEmails].map(email => items.find(item => item.email === email));
Понятно, что код туловый, но можно вообще в один проход: 

```javascript
const uniqueEmails = new Set();
return items.reduce((accum, item) => {
    if (! uniqueEmails.has(item.email)) {
        uniqueEmails.add(item.email);
        accum.push(item)
    }
    return accum
}, [])
```

2021-02-27 15:08 UTC, artembert commented on src/service/server/data-access/fill-db.ts
> +  return [...uniqueEmails].map(email => items.find(item => item.email === email));
Элегантное решение, спасибо

2021-02-27 15:20 UTC, LordotU approved these changes

2021-02-27 15:50 UTC, LordotU approved these changes

2021-02-27 15:50 UTC, merged